### ISSUE TITLE
Run it, But it show:  please fix the size() line to continue.

### ISSUE THREAD

**Issue by NeoTim** [biomurph/OpenBCI_GUI_Helicopter_Throttle#1]
HexBug(Serial serialPort) {
    int ID = 0;//  display comands
command_forward = new Command(serialPort,"O","Swim!",ID++);
   command_right = new Command(serialPort,"|","Right",ID++);
   command_left = new Command(serialPort,"{","Left",ID++);
   command_climb = new Command(serialPort,"}","Climb",ID++);
   command_dive = new Command(serialPort,"P","Dive",ID++);
     

![screen shot 2017-06-14 at 5 34 06 pm](https://user-images.githubusercontent.com/14356809/27160326-3afa73e0-5128-11e7-9da2-39753c35a289.png)

**Comment by biomurph** [comment]
Hi,

I'm not sure why you are getting that error. The Command(Serial,String,String,Int) is defined in the Helecopter.pde file.

**Comment by NeoTim** [comment]
yes.  The Command(Serial,String,String,Int) is defined above. but it say OpenBCI_GUI.HexBug.Command is undefined
![screen shot 2017-06-19 at 10 20 50 am](https://user-images.githubusercontent.com/14356809/27297305-2d9d83a4-54d9-11e7-8b9f-c94ffe68b8bf.png)
