### ISSUE TITLE
 It all took about half a month of hacking on your code. but it does not work.

### ISSUE THREAD

**Issue by NeoTim** [biomurph/OpenBCI_GUI_Helicopter_Throttle#3]
![screen shot 2017-06-19 at 11 03 37 am](https://user-images.githubusercontent.com/14356809/27308781-5bac25b2-5505-11e7-96da-b43c2c7aea3a.png)

**Comment by biomurph** [comment]
I have just run this sketch on my computer and I do not get this error.
macbookPRO, macOS 10.12.5
I ran it with the synthetic data and the file playback data.
In the main OpenBCI_GUI.pde file, you need to specify your external Arduino that you want to control the Helicopter on code line 113.

Did you make any changes to the sketch? If you did, please link me to your repo and maybe we can find the problem by comparing it to this code.

**Comment by NeoTim** [comment]
I just download it , open , and run. I have no synthetic data and the file playback data.
I did not change anything.  can u give your synthetic data and the file playback data.
My line 113 is int hexBug_baud = 115200;
 and my  Arduino is   Serial.begin(115200);
![screen shot 2017-06-20 at 2 30 42 pm](https://user-images.githubusercontent.com/14356809/27356973-56c92d2c-55c5-11e7-9d60-3e352a044b4f.png)
![screen shot 2017-06-20 at 2 30 21 pm](https://user-images.githubusercontent.com/14356809/27356977-5a37fdbc-55c5-11e7-8865-e982cb5cdee4.png)
![screen shot 2017-06-20 at 2 29 57 pm](https://user-images.githubusercontent.com/14356809/27356979-5d7884a6-55c5-11e7-97f4-a366f91a27b6.png)

**Comment by biomurph** [comment]
We may be working off of different code bases.
I am referring to the code that resides in this repo
https://github.com/biomurph/OpenBCI_GUI_Helicopter_Throttle
Which is the code repo that you are creating an issue in.
Where did you get your code?

**Comment by NeoTim** [comment]
In the beginning , get from https://github.com/viguix/OpenBCI_GUI_Helicopter_Throttle

and it does not work.

then I get the code from this repo.

Thank you
