### ISSUE TITLE
measure the wires that connect to the helicopter controller and find it is successfully changing the resistance  from 0.58KΩ to 0.66KΩ.   Are these data correct?

### ISSUE THREAD

**Issue by NeoTim** [biomurph/OpenBCI_GUI_Helicopter_Throttle#6]
measure the wires that connect to the helicopter controller and find it is successfully changing the resistance  from 0.58KΩ to 0.66KΩ.   
the Received in log is always $.
and the trottle in log is from 0 to 24.
Are these data correct?

![_20170622170303](https://user-images.githubusercontent.com/14356809/27461045-bc62e4d6-576c-11e7-88ac-2ab82f00550a.jpg)

**Comment by NeoTim** [comment]
how to change the resistance from [0.58KΩ , 0.66KΩ]  to  [1.0KΩ , 1.3KΩ]?

[1.0KΩ , 1.3KΩ] can fly. but now is [0.58KΩ , 0.66KΩ] .

Which code is to control the resistance?

**Comment by neotim** [comment]
[1.0KΩ , 1.3KΩ] can fly.  but now is  [0.58KΩ , 0.66KΩ] .

**Comment by biomurph** [comment]
The Processing sketch sends a $ to tell the arduino that the next character is the throttle control.
Throttle control is coded from 'A' to 'Z' = 0 to 26.

**Comment by NeoTim** [comment]
yes , I saw them in the code annotation:
     case '$':  // Processing must send the $ to tell Arduino the next value is special
    byte(inChar - 'A'); // variable is ascii encoded 0=A, 1=B, etc
 
is this function below control the resistance?

void setWiper0(byte address, byte val){
  Wire.beginTransmission(address);  // start transmission to slave 0x
  Wire.write(WRITE_P0);      // sends instruction byte
  Wire.write(val);             // sends potentiometer value byte
  Wire.endTransmission();      // stop transmitting
}

**Comment by biomurph** [comment]
I do not believe that funciton exists in this code base which you are bringin this issue up on.
I can only respond to issues in this code base. 
Please take this issue to the repo where you got the code.

**Comment by NeoTim** [comment]
you r right, I'm confusing the code ...
The OpenBCI_GUI code is yours.
That Arduino code is mixed.

I have solved the problem.
My approach is change 1KΩ resistance to 0.5KΩ.
Thank you very much for your help these days.
